import { ArrowRight, BarChart3, Briefcase, Building2, CheckCircle2, Globe2, MapPin, Phone, ShoppingCart, Sparkles, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import AddOnsSection from '../components/AddOnsSection';
import GlobalFooter from '../components/GlobalFooter';
import GlobalHeader from '../components/GlobalHeader';

const industries = [
  { name: 'Small Business', description: 'A clean CRM for service businesses, contractors, consultants, and local teams.', path: '/small-business-crm', icon: Briefcase, startingAt: 29 },
  { name: 'Restaurant / Retail + POS', description: 'Customer management and POS workflows for restaurants, shops, and retail operations.', path: '/restaurant-retail-crm', icon: ShoppingCart, startingAt: 69 },
  { name: 'Professional CRM', description: 'Industry-focused CRM for real estate, mortgage, legal, healthcare, and other professional teams.', path: '/platform', icon: Building2, startingAt: 49 },
];
const capabilities = [
  { icon: Users, title: 'Customers & Contacts', description: 'Keep people, companies, notes, tasks, and activity organized in one place.' },
  { icon: BarChart3, title: 'Pipelines & Opportunities', description: 'Track leads and opportunities through clear stages with less manual follow-up.' },
  { icon: Sparkles, title: 'Automation & AI', description: 'Use intelligent assistance and workflows to reduce repetitive work across the CRM.' },
  { icon: Globe2, title: 'Industry Workflows', description: 'Start with workflows designed around the way your industry actually operates.' },
];
const phaseTwo = [
  { icon: Phone, name: 'Phone System', description: 'Integrated business calling and communications with separate add-on pricing.' },
  { icon: Sparkles, name: 'Social Publisher Pro', description: 'Social publishing, planning, approvals, and campaign tools as a paid add-on.' },
  { icon: MapPin, name: 'Geofencing / Location Marketing', description: 'Location-aware marketing and geofence capabilities offered separately from the base CRM.' },
];

export default function MarketingHome() {
  return <div className="min-h-screen bg-white text-slate-900"><GlobalHeader /><main id="main-content" className="pt-20">
    <section className="relative overflow-hidden border-b border-slate-200 bg-gradient-to-b from-cyan-50 via-white to-white"><div className="mx-auto grid max-w-7xl gap-12 px-4 py-20 sm:px-6 lg:grid-cols-2 lg:items-center lg:px-8 lg:py-28"><div><span className="inline-flex rounded-full border border-cyan-200 bg-white px-4 py-2 text-xs font-bold uppercase tracking-[0.18em] text-cyan-700">CRM + operations for modern businesses</span><h1 className="mt-6 text-4xl font-bold tracking-tight text-slate-950 sm:text-5xl lg:text-6xl">Run your customer relationships and daily operations from one cleaner system.</h1><p className="mt-6 text-lg leading-8 text-slate-600">OPERON CRM brings customer management, pipelines, tasks, automation, and industry-focused workflows together without forcing your team to juggle disconnected tools.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/start" className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-6 py-3.5 font-semibold text-white">Get Started<ArrowRight className="h-4 w-4" /></Link><Link to="/pricing" className="rounded-xl border border-slate-300 bg-white px-6 py-3.5 font-semibold text-slate-800">View Pricing</Link></div><div className="mt-8 flex flex-wrap gap-5 text-sm text-slate-600">{['Simple monthly pricing','Industry-focused options','Phase 2 add-ons shown separately'].map(item=><span key={item} className="inline-flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-600" />{item}</span>)}</div></div><div className="rounded-[2rem] border border-slate-200 bg-white p-7 shadow-xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-cyan-700">OPERON workspace</p><h2 className="mt-2 text-2xl font-bold">Business overview</h2><div className="mt-6 grid gap-4 sm:grid-cols-3">{[['Open Leads','24'],['Opportunities','12'],['Tasks Due','7']].map(([l,v])=><div key={l} className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-500">{l}</p><p className="mt-2 text-2xl font-bold">{v}</p></div>)}</div></div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-cyan-700">Choose your starting point</p><h2 className="mt-2 text-3xl font-bold text-slate-950">One OPERON platform, sized for the way you work.</h2><div className="mt-8 grid gap-5 lg:grid-cols-3">{industries.map(industry=>{const Icon=industry.icon;return <article key={industry.name} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><Icon className="h-7 w-7 text-cyan-700"/><h3 className="mt-5 text-xl font-bold">{industry.name}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{industry.description}</p><p className="mt-5 text-sm text-slate-500">Starting at <strong className="text-2xl text-slate-950">${industry.startingAt}</strong>/mo</p><Link to={industry.path} className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-cyan-700">Explore solution<ArrowRight className="h-4 w-4"/></Link></article>})}</div></section>
    <section className="border-y border-slate-200 bg-slate-50"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><h2 className="text-3xl font-bold">Core platform</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{capabilities.map(c=>{const Icon=c.icon;return <article key={c.title} className="rounded-2xl border border-slate-200 bg-white p-5"><Icon className="h-5 w-5 text-slate-700"/><h3 className="mt-4 font-bold">{c.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{c.description}</p></article>})}</div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="rounded-[2rem] border border-violet-100 bg-violet-50/50 p-8"><span className="rounded-full bg-white px-4 py-2 text-xs font-bold text-violet-700">PHASE 2 · COMING SOON</span><h2 className="mt-5 text-3xl font-bold">High-value add-ons are coming next.</h2><div className="mt-8 grid gap-5 lg:grid-cols-3">{phaseTwo.map(item=>{const Icon=item.icon;return <article key={item.name} className="rounded-2xl bg-white p-6"><Icon className="h-5 w-5 text-violet-700"/><h3 className="mt-4 font-bold">{item.name}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{item.description}</p></article>})}</div></div></section><section className="mx-auto max-w-7xl px-4 pb-16 sm:px-6 lg:px-8"><AddOnsSection /></section>
  </main><GlobalFooter /></div>;
}
