import { Link } from 'react-router-dom';
import { BadgePercent, CalendarCheck, Layers3 } from 'lucide-react';
import GlobalHeader from '../components/GlobalHeader';
import GlobalFooter from '../components/GlobalFooter';
import PricingFamilySection from '../components/PricingFamilySection';
import AddOnsSection from '../components/AddOnsSection';
import { clientPaidThirdPartyServices, pricingFamilies, pricingRules } from '../lib/pricing';

export default function PricingPage() {
  return <div className="min-h-screen bg-white text-slate-900"><GlobalHeader/><main id="main-content" className="pt-20">
    <section className="relative overflow-hidden border-b border-slate-200 bg-gradient-to-b from-cyan-50 via-white to-white"><div className="absolute inset-x-0 top-0 h-72 bg-[radial-gradient(circle_at_top_left,rgba(6,182,212,0.14),transparent_45%),radial-gradient(circle_at_top_right,rgba(124,58,237,0.10),transparent_38%)]"/><div className="relative mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-24"><div className="max-w-4xl"><span className="inline-flex rounded-full border border-cyan-200 bg-white px-4 py-2 text-xs font-bold uppercase tracking-[0.18em] text-cyan-700 shadow-sm">OPERON systems & pricing</span><h1 className="mt-6 text-4xl font-bold tracking-tight text-slate-950 sm:text-5xl lg:text-6xl">One OPERON platform. Pricing that reflects each business system.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-600">Each major OPERON system has its own tier structure. Restaurant / Retail / Clubs, Real Estate, Mortgage, and Gun / FFL launch prices are being finalized rather than publishing the older prices you have already rejected.</p></div>
    <div className="mt-10 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><CalendarCheck className="h-6 w-6 text-emerald-600"/><h2 className="mt-3 font-bold">10% annual full-pay savings</h2><p className="mt-1 text-sm text-slate-600">{pricingRules.annual}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Layers3 className="h-6 w-6 text-cyan-700"/><h2 className="mt-3 font-bold">15% qualifying combo savings</h2><p className="mt-1 text-sm text-slate-600">{pricingRules.combo}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><BadgePercent className="h-6 w-6 text-violet-700"/><h2 className="mt-3 font-bold">Discount lockout</h2><p className="mt-1 text-sm text-slate-600">{pricingRules.lockout}</p></div></div>
    <div className="mt-8 flex flex-wrap gap-2">{pricingFamilies.map((family)=><a key={family.id} href={`#${family.id}`} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 shadow-sm hover:border-cyan-300 hover:text-cyan-700">{family.name}</a>)}</div></div></section>
    <section className="mx-auto max-w-7xl space-y-20 px-4 py-16 sm:px-6 lg:px-8 lg:py-20">{pricingFamilies.map((family)=><PricingFamilySection key={family.id} family={family}/>)}<AddOnsSection/>
      <section className="grid gap-6 rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm sm:p-8 lg:grid-cols-[1.4fr_1fr] lg:p-10"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-cyan-700">Third-party services</p><h2 className="mt-2 text-3xl font-bold tracking-tight text-slate-950">Provider subscriptions stay transparent.</h2><p className="mt-3 max-w-3xl text-slate-600">Customer-owned subscriptions and usage charges remain separate unless an OPERON plan or add-on explicitly includes them.</p></div><div className="rounded-2xl bg-slate-50 p-5"><ul className="space-y-3 text-sm text-slate-700">{clientPaidThirdPartyServices.map((service)=><li key={service} className="flex gap-3"><span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-cyan-600"/><span>{service}</span></li>)}</ul></div></section>
      <section className="rounded-[2rem] bg-slate-950 px-6 py-10 text-white sm:px-8 lg:flex lg:items-center lg:justify-between lg:px-10"><div className="max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-cyan-300">Need help choosing?</p><h2 className="mt-2 text-3xl font-bold tracking-tight">We can match the system and tier to your operation.</h2><p className="mt-3 text-slate-300">Tell us your industry, team size, locations, and workflow needs.</p></div><div className="mt-7 flex flex-wrap gap-3 lg:mt-0"><Link to="/contact" className="rounded-xl bg-white px-5 py-3 text-sm font-semibold text-slate-950 hover:bg-slate-100">Contact Sales</Link><Link to="/start" className="rounded-xl border border-slate-700 px-5 py-3 text-sm font-semibold text-white hover:border-cyan-400 hover:text-cyan-200">Get Started</Link></div></section>
    </section></main><GlobalFooter/></div>;
}
