import { Link } from 'react-router-dom';
import { BadgePercent, CalendarCheck, Layers3, PlugZap } from 'lucide-react';
import GlobalHeader from '../components/GlobalHeader';
import GlobalFooter from '../components/GlobalFooter';
import PricingFamilySection from '../components/PricingFamilySection';
import AddOnsSection from '../components/AddOnsSection';
import { clientPaidThirdPartyServices, pricingFamilies, pricingRules } from '../lib/pricing';

const integrations = ['QuickBooks', 'Gusto', 'DocuSign', 'Slack', 'Google Workspace', 'Microsoft 365', 'Square', 'PayPal', 'Telnyx', 'APIs & Webhooks'];

export default function PricingPage() {
  return <div className="min-h-screen bg-white text-slate-900"><GlobalHeader/><main id="main-content" className="pt-20">
    <section className="relative overflow-hidden border-b border-slate-200 bg-gradient-to-b from-cyan-50 via-white to-white text-center"><div className="absolute inset-x-0 top-0 h-72 bg-[radial-gradient(circle_at_top_left,rgba(6,182,212,0.14),transparent_45%),radial-gradient(circle_at_top_right,rgba(124,58,237,0.10),transparent_38%)]"/><div className="relative mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-24"><div className="mx-auto max-w-4xl"><span className="inline-flex rounded-full border border-cyan-200 bg-white px-4 py-2 text-xs font-bold uppercase tracking-[0.18em] text-cyan-700 shadow-sm">OPERON systems & pricing</span><h1 className="mt-6 text-4xl font-bold tracking-tight text-slate-950 sm:text-5xl lg:text-6xl">Plans built to grow with your operation.</h1><p className="mx-auto mt-6 max-w-3xl text-lg leading-8 text-slate-600">Choose the OPERON service that fits your business, compare what each higher tier adds, then enrich the system with compatible products and add-ons.</p></div>
    <div className="mt-10 grid items-stretch gap-4 md:grid-cols-3"><div className="flex h-full flex-col items-center rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><CalendarCheck className="h-6 w-6 text-emerald-600"/><h2 className="mt-3 font-bold">10% annual full-pay savings</h2><p className="mt-1 text-sm text-slate-600">{pricingRules.annual}</p></div><div className="flex h-full flex-col items-center rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Layers3 className="h-6 w-6 text-cyan-700"/><h2 className="mt-3 font-bold">15% qualifying combo savings</h2><p className="mt-1 text-sm text-slate-600">{pricingRules.combo}</p></div><div className="flex h-full flex-col items-center rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><BadgePercent className="h-6 w-6 text-violet-700"/><h2 className="mt-3 font-bold">Discount lockout</h2><p className="mt-1 text-sm text-slate-600">{pricingRules.lockout}</p></div></div>
    <div className="mt-8 flex flex-wrap justify-center gap-2">{pricingFamilies.map((family)=><a key={family.id} href={`#${family.id}`} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 shadow-sm hover:border-cyan-300 hover:text-cyan-700">{family.name}</a>)}</div></div></section>
    <section className="mx-auto max-w-[96rem] space-y-20 px-4 py-16 sm:px-6 lg:px-8 lg:py-20">{pricingFamilies.map((family)=><PricingFamilySection key={family.id} family={family}/>)}<AddOnsSection/>
      <section className="rounded-[2rem] border border-slate-200 bg-gradient-to-b from-slate-50 to-white p-6 text-center shadow-sm sm:p-8 lg:p-10"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-violet-100 text-violet-700"><PlugZap className="h-6 w-6"/></div><p className="mt-5 text-sm font-semibold uppercase tracking-[0.18em] text-violet-700">Integrations</p><h2 className="mt-2 text-3xl font-bold tracking-tight text-slate-950">Connect the tools your business already relies on.</h2><p className="mx-auto mt-3 max-w-3xl text-slate-600">OPERON is designed to connect CRM and operations with accounting, workforce, documents, communications, payments and automation. Availability depends on the selected system, plan and provider configuration.</p><div className="mx-auto mt-8 grid max-w-5xl gap-3 sm:grid-cols-2 md:grid-cols-5">{integrations.map((name)=><div key={name} className="flex min-h-20 items-center justify-center rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-slate-700 shadow-sm">{name}</div>)}</div><Link to="/integrations" className="mt-8 inline-flex rounded-xl bg-slate-950 px-6 py-3 text-sm font-semibold text-white hover:bg-slate-800">Browse integrations</Link></section>
      <section className="rounded-[2rem] border border-slate-200 bg-white p-6 text-center shadow-sm sm:p-8 lg:p-10"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-cyan-700">Third-party costs</p><h2 className="mt-2 text-3xl font-bold tracking-tight text-slate-950">Provider subscriptions and usage stay transparent.</h2><p className="mx-auto mt-3 max-w-3xl text-slate-600">Third-party subscriptions, transaction fees, advertising/media spend, telecommunications usage and provider charges are not included unless specifically stated.</p><div className="mx-auto mt-6 flex max-w-4xl flex-wrap justify-center gap-2">{clientPaidThirdPartyServices.map((service)=><span key={service} className="rounded-full bg-slate-100 px-4 py-2 text-sm font-medium text-slate-700">{service}</span>)}</div></section>
      <section className="rounded-[2rem] bg-slate-950 px-6 py-10 text-center text-white sm:px-8 lg:px-10"><div className="mx-auto max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-cyan-300">Build your OPERON</p><h2 className="mt-2 text-3xl font-bold tracking-tight">Choose the service first. Add the tools that make it fit.</h2><p className="mt-3 text-slate-300">Tell us your industry, team size, locations and workflow needs. We can help match the base system, tier and add-ons.</p></div><div className="mt-7 flex flex-wrap justify-center gap-3"><Link to="/contact" className="rounded-xl bg-white px-5 py-3 text-sm font-semibold text-slate-950 hover:bg-slate-100">Contact Sales</Link><Link to="/start" className="rounded-xl border border-slate-700 px-5 py-3 text-sm font-semibold text-white hover:border-cyan-400 hover:text-cyan-200">Get Started</Link></div></section>
    </section></main><GlobalFooter/></div>;
}
