import { Link } from 'react-router-dom';
import { ArrowRight, BarChart3, CalendarDays, CheckCircle2, FileCheck2, Layers3, MapPin, Megaphone, MessageSquareText, Share2, Sparkles, Users2, WandSparkles } from 'lucide-react';
import GlobalHeader from '../components/GlobalHeader';
import GlobalFooter from '../components/GlobalFooter';

const capabilities = [
  { icon: CalendarDays, title: 'Unified content calendar', text: 'Planned capability for organizing client and brand content across supported channels with campaign context attached.' },
  { icon: Share2, title: 'Multi-channel publishing', text: 'Planned publishing workflows for supported social networks, subject to provider APIs, approvals, and account eligibility.' },
  { icon: WandSparkles, title: 'AI content assistance', text: 'Planned assistance for ideas, drafts, variations, captions, and campaign concepts with human review before publishing.' },
  { icon: FileCheck2, title: 'Approvals & collaboration', text: 'Planned teammate and client review workflows before content is scheduled or published.' },
  { icon: Users2, title: 'Client & brand workspaces', text: 'Planned workspaces for organizing brands, assets, campaigns, and publishing activity inside OPERON.' },
  { icon: BarChart3, title: 'Campaign performance', text: 'Planned reporting that connects publishing activity and supported engagement signals to CRM follow-up.' },
];
const workflow = ['Create campaign', 'Build content', 'Review & approve', 'Schedule & publish', 'Track engagement', 'CRM follow-up'];

export default function SocialMediaMarketingPage() {
  return <div className="min-h-screen bg-white text-slate-900"><GlobalHeader/><main id="main-content" className="pt-20">
    <section className="relative overflow-hidden border-b border-blue-100 bg-[radial-gradient(circle_at_75%_20%,rgba(124,58,237,.14),transparent_28rem),radial-gradient(circle_at_15%_35%,rgba(6,182,212,.11),transparent_22rem),linear-gradient(180deg,#f8fbff_0%,#ffffff_86%)]"><div className="relative mx-auto grid max-w-7xl gap-12 px-4 py-20 sm:px-6 lg:grid-cols-[.92fr_1.08fr] lg:items-center lg:px-8 lg:py-24"><div><span className="inline-flex rounded-full border border-violet-200 bg-white px-4 py-2 text-xs font-black uppercase tracking-[.18em] text-violet-700">Phase 2 · Coming Soon</span><p className="mt-5 text-sm font-black uppercase tracking-[.18em] text-blue-700">OPERON Social Publisher Pro™</p><h1 className="mt-3 text-5xl font-black tracking-[-.055em] text-slate-950 sm:text-6xl">YOUR SOCIAL,<br/><span className="bg-gradient-to-r from-blue-600 via-cyan-500 to-violet-600 bg-clip-text text-transparent">IN SYNC.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">A planned OPERON add-on for creating, reviewing, publishing, and measuring social campaigns alongside CRM workflows. Provider connections and production publishing are still being completed and certified.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/contact" className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-6 py-3.5 font-black text-white hover:bg-blue-700">Join the interest list<ArrowRight className="h-4 w-4"/></Link><Link to="/pricing" className="rounded-xl border border-slate-300 bg-white px-6 py-3.5 font-black text-slate-800">View current plans</Link></div><div className="mt-8 flex flex-wrap gap-4 text-sm font-semibold text-slate-600">{['CRM-connected design','Human approval controls','Provider-dependent publishing'].map(x=><span key={x} className="inline-flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-600"/>{x}</span>)}</div></div><div className="rounded-[30px] border border-slate-200 bg-white p-6 shadow-2xl"><div className="flex items-center gap-3"><Megaphone className="h-6 w-6 text-violet-600"/><div><p className="font-black">Product concept preview</p><p className="text-xs text-slate-500">Illustrative UI — not live social-account data</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-3">{[['Scheduled','—'],['Approvals','—'],['Campaigns','—']].map(([l,v])=><div key={l} className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-500">{l}</p><p className="mt-2 text-2xl font-black">{v}</p></div>)}</div><div className="mt-4 rounded-2xl bg-gradient-to-br from-blue-600 to-violet-600 p-5 text-white"><Sparkles className="h-5 w-5"/><p className="mt-3 font-black">Human-reviewed AI assistance</p><p className="mt-2 text-sm text-white/80">Planned workflow: generate → review → approve → publish.</p></div></div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><p className="text-sm font-black uppercase tracking-[.18em] text-blue-700">Planned capabilities</p><h2 className="mt-3 max-w-3xl text-3xl font-black sm:text-4xl">Social publishing should not live in a disconnected tool.</h2><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{capabilities.map(({icon:Icon,title,text})=><article key={title} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50"><Icon className="h-5 w-5 text-blue-600"/></div><h3 className="mt-5 text-lg font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></section>
    <section className="border-y border-slate-200 bg-slate-50"><div className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><p className="text-sm font-black uppercase tracking-[.18em] text-violet-700">Target workflow</p><div className="mt-8 grid gap-3 md:grid-cols-3 lg:grid-cols-6">{workflow.map((step,i)=><div key={step} className="rounded-2xl border border-slate-200 bg-white p-5"><span className="text-xs font-black text-blue-600">0{i+1}</span><p className="mt-3 text-sm font-black">{step}</p></div>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div className="grid gap-6 overflow-hidden rounded-[2rem] bg-slate-950 p-8 text-white lg:grid-cols-[1.05fr_.95fr] lg:p-12"><div><div className="flex items-center gap-3"><MapPin className="h-6 w-6 text-cyan-400"/><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-300">Geofence Marketing</p></div><h2 className="mt-4 text-3xl font-black">Location-aware campaigns are also a separate Phase 2 capability.</h2><p className="mt-4 max-w-2xl text-slate-300">Availability depends on provider support, consent requirements, account eligibility, and production certification. Variable provider and campaign costs remain outside the base CRM subscription.</p></div><div className="grid gap-3 sm:grid-cols-2">{[['Audience zones',Layers3],['Campaign messaging',MessageSquareText],['CRM follow-up',Users2],['Performance view',BarChart3]].map(([label,Icon])=><div key={label as string} className="rounded-2xl border border-white/10 bg-white/5 p-5"><Icon className="h-5 w-5 text-cyan-300"/><p className="mt-3 font-black">{label as string}</p></div>)}</div></div></section>
  </main><GlobalFooter/></div>;
}
