import { Boxes, CheckCircle2, Sparkles } from 'lucide-react';
import { addOnCatalog, recommendedStacks } from '../lib/pricing';

const categories = ['Capacity', 'Growth', 'Operations', 'Branding', 'Phase 2'] as const;

export default function AddOnsSection() {
  return <section className="rounded-[2rem] border border-slate-200 bg-slate-50 p-6 text-center sm:p-8 lg:p-10">
    <div className="mx-auto max-w-3xl"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-cyan-100 text-cyan-800"><Boxes className="h-6 w-6"/></div><p className="mt-5 text-sm font-semibold uppercase tracking-[.18em] text-cyan-700">Products & add-ons</p><h2 className="mt-2 text-3xl font-bold tracking-tight text-slate-950">Enrich your OPERON system with more capability</h2><p className="mt-3 text-slate-600">Choose the base service first, then add only the capacity, growth, operations and branding tools that fit the business.</p></div>
    <div className="mt-10 space-y-10">{categories.map((category)=>{const items=addOnCatalog.filter((item)=>item.category===category);return <div key={category}><div className="mb-5 flex items-center gap-4"><div className="h-px flex-1 bg-slate-200"/><h3 className="text-sm font-bold uppercase tracking-[.16em] text-slate-500">{category==='Phase 2'?'Phase 2 · Coming Soon':category}</h3><div className="h-px flex-1 bg-slate-200"/></div><div className="grid items-stretch gap-4 md:grid-cols-2 xl:grid-cols-4">{items.map((addon)=><article key={addon.name} className={`flex h-full min-h-56 flex-col items-center rounded-2xl border bg-white p-5 shadow-sm ${addon.phaseTwo?'border-violet-200':'border-slate-200'}`}><h4 className="font-bold text-slate-950">{addon.name}</h4><p className="mt-2 text-lg font-bold text-cyan-700">{addon.price}</p><p className="mt-3 flex-1 text-sm leading-6 text-slate-600">{addon.description}</p>{addon.setupFee&&<p className="mt-4 rounded-xl bg-amber-50 px-3 py-2 text-xs font-semibold text-amber-900">{addon.setupFee}</p>}{addon.phaseTwo&&<span className="mt-4 rounded-full bg-violet-50 px-3 py-1 text-xs font-bold text-violet-700">Phase 2 · Coming Soon</span>}</article>)}</div></div>})}</div>
    <div className="mt-12 rounded-3xl border border-cyan-200 bg-white p-6 sm:p-8"><Sparkles className="mx-auto h-7 w-7 text-cyan-700"/><h3 className="mt-3 text-2xl font-bold text-slate-950">Bundle & save</h3><p className="mx-auto mt-2 max-w-3xl text-sm leading-6 text-slate-600">Choose 2 or more qualifying OPERON add-ons and save 15% on the eligible add-on subtotal. Annual and combo discounts do not stack; the best eligible automatic discount applies.</p><div className="mt-7 grid items-stretch gap-4 md:grid-cols-2 xl:grid-cols-4">{recommendedStacks.map((stack)=><article key={stack.system} className="flex h-full flex-col rounded-2xl border border-slate-200 bg-slate-50 p-5 text-left"><h4 className="text-center font-bold text-slate-950">{stack.system}</h4><ul className="mt-4 space-y-2">{stack.items.map((item)=><li key={item} className="flex items-start gap-2 text-sm text-slate-600"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600"/><span>{item}</span></li>)}</ul></article>)}</div></div>
  </section>;
}
